# CodeVoyager GitHub Backup Script
param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

Write-Host "🚀 Starting CodeVoyager GitHub Backup..." -ForegroundColor Green

# Create timestamp
$TIMESTAMP = Get-Date -Format "yyyyMMdd-HHmmss"
$BACKUP_DIR = ".\backups"

# Create backup directory
if (-not (Test-Path $BACKUP_DIR)) {
    New-Item -ItemType Directory -Path $BACKUP_DIR -Force
}

# Create backup
Write-Host "📦 Creating backup..." -ForegroundColor Blue
$backupFile = "$BACKUP_DIR\codevoyager-github-backup-$TIMESTAMP.zip"

$filesToBackup = @(
    ".\src",
    ".\package.json", 
    ".\docker-compose.yml",
    ".\docker-compose.web.yml",
    ".\Dockerfile",
    ".\Dockerfile.web",
    ".\scripts",
    ".\.github"
)

Compress-Archive -Path $filesToBackup -DestinationPath $backupFile -Force
Write-Host "✅ Backup created: $backupFile" -ForegroundColor Green

# Git operations
Write-Host "📋 Git operations..." -ForegroundColor Blue

try {
    # Check git status
    $gitStatus = git status --porcelain
    
    if ($gitStatus -or $Force) {
        Write-Host "🔄 Committing changes..." -ForegroundColor Blue
        
        # Add all changes
        git add .
        
        # Create commit
        $commitMessage = "GitHub backup - $TIMESTAMP

Files included:
- Complete source code backup
- Docker configurations  
- GitHub Actions workflow
- Backup scripts
- Package configurations

Generated by: github-backup.ps1
Timestamp: $TIMESTAMP"
        
        git commit -m $commitMessage
        Write-Host "✅ Changes committed" -ForegroundColor Green
        
        # Push to GitHub
        Write-Host "🚀 Pushing to GitHub..." -ForegroundColor Blue
        git push origin main
        Write-Host "✅ Pushed to GitHub" -ForegroundColor Green
    } else {
        Write-Host "ℹ️ No changes to commit" -ForegroundColor Cyan
    }
    
    # Create Git backup files
    git log --oneline -10 | Out-File "$BACKUP_DIR\git-commits-$TIMESTAMP.txt"
    git status --porcelain | Out-File "$BACKUP_DIR\git-status-$TIMESTAMP.txt"
    Write-Host "✅ Git backup created" -ForegroundColor Green
    
} catch {
    Write-Host "❌ Git operations failed: $($_.Exception.Message)" -ForegroundColor Red
    if (-not $Force) {
        return
    }
}

# Create summary
Write-Host "📊 Creating summary..." -ForegroundColor Blue
$backupSize = [math]::Round((Get-Item $backupFile).Length / 1MB, 2)

$summary = @"
# CodeVoyager GitHub Backup Summary
**Timestamp**: $TIMESTAMP
**Status**: ✅ **SUCCESS**

## 📦 Backup Information
- **Backup File**: `codevoyager-github-backup-$TIMESTAMP.zip`
- **Size**: $backupSize MB
- **Location**: `$BACKUP_DIR`

## 🚀 GitHub Status
- **Repository**: https://github.com/Rftmxqgx1/codevoyager.git
- **Push Status**: ✅ Completed
- **Actions**: https://github.com/Rftmxqgx1/codevoyager/actions

## 📋 Files Created
- `codevoyager-github-backup-$TIMESTAMP.zip` - Complete project backup
- `git-commits-$TIMESTAMP.txt` - Recent commit history
- `git-status-$TIMESTAMP.txt` - Git working directory status

## 🔗 Important Links
- **GitHub Repository**: https://github.com/Rftmxqgx1/codevoyager.git
- **Actions Tab**: https://github.com/Rftmxqgx1/codevoyager/actions
- **Local Development**: http://localhost:3001
- **Docker Production**: http://localhost:3000

---
*Generated by CodeVoyager GitHub Backup System*
*Timestamp: $TIMESTAMP*
"@

$summary | Out-File "$BACKUP_DIR\github-backup-summary-$TIMESTAMP.md"
Write-Host "✅ Summary created" -ForegroundColor Green

# Display results
Write-Host "🎉 GitHub Backup Completed Successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📁 Backup Location: $BACKUP_DIR" -ForegroundColor Cyan
Write-Host "📦 Main Backup: $backupFile" -ForegroundColor Cyan
Write-Host "📊 Summary: $BACKUP_DIR\github-backup-summary-$TIMESTAMP.md" -ForegroundColor Cyan
Write-Host ""
Write-Host "🔗 GitHub Repository: https://github.com/Rftmxqgx1/codevoyager.git" -ForegroundColor Blue
Write-Host "🔗 Actions: https://github.com/Rftmxqgx1/codevoyager/actions" -ForegroundColor Blue
Write-Host ""

# Display summary
Get-Content "$BACKUP_DIR\github-backup-summary-$TIMESTAMP.md"
